# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    img_gallery_accueil: '%kernel.project_dir%/public/images/uploads/imggalleryaccueil'
    img_teacher: '%kernel.project_dir%/public/images/uploads/imgteacher'
    img_carousel: '%kernel.project_dir%/public/images/uploads/carousel'
    document_lesson: '%kernel.project_dir%/public/documents/lesson/'
    document_exam: '%kernel.project_dir%/public/documents/exam/'
    videos_lesson: '%kernel.project_dir%/public/videos/lesson/'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    # App\Twig\Extension\FileExtension: ~
        # resource: '../src/Twig/Extension'
        # tags:
        #     - { name: twig.extension }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
